# Site settings
title: Palmaz Ahmad
email: palmaz.ahmad@hotmail.com
url: https://www.palmazahmad.com
description: "Webpage Containg Palmaz Ahmads portfolio. This includes a Blog and Projects both previously worked on and current."
keywords: "your keywords, separated by commas"
skills: "Data Analyst - Student - Martial Artist"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Palmaz

collections:
  projects:


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2d8984  #3AAFA9 #39a0ca  #A64AC9 #47cc66 #9615bd # #80B3FF
  primary-rgb: '45,137,132' #"24,288,156" #"128,179,255"
  secondary:  551a8b #508b1a #842d89 #9068be #a0ca39 #6dc94a #17252A #FD6E8A
  secondary-dark: 3cb5af #2d8984 #ca39a0  #2B7A78 #A2122F

# Footer settings
footer:
  copyright: Palmaz Ahmad
  quote: Quote of the day
  social: Find me on
  blog: Blog

# Social networks usernames
social:
  - title: linkedin
    url: https://www.linkedin.com/in/palmaz
  - title: twitter
    url: http://twitter.com/palmazahmadd
  # - title: facebook
  #   url: https://www.facebook.com/palmaz.ahmad.1
  - title: instagram
    url: http://instagram.com/palmazahmad
  - title: github
    url: http://github.com/palmazahmad

# Quotes - need to add one often
quote: “The purpose of life is a life with a purpose. So I’d rather die for a cause, than live a life that is worthless.” – Immortal Technique


# Blog content
blog: 'My Blog contains all my own thoughts and learings which must not be taken as anything else.'

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"
      author: "Posted by - Palmaz Ahmad on "
      permalink: /:categories/:title/
      
     
      
      

